config/routes.rb
Auth::Application.routes.draw do

  get "users/desbloqueio"

  get "users/bloqueio"

  get "users/relatorio"

  get "users/mostrarDica"

  get "users/lembrar_senha"

  get "users/alter"

  get "home/index"
  
  get "authentications/loga"
  
  get "authentications/desloga"

  resources :logins

  resources :log_gerals

  resources :tipologs

  resources :users

  resources :statuses

  resources :usertypes

  resources :sistemas
  

  root :to => 'home#index'

end

app/models/sistema.rb
class Sistema < ActiveRecord::Base
  attr_accessible :key, :nome
end

app/controllers/sistemas_controller.rb
class SistemasController < ApplicationController
  # GET /sistemas
  # GET /sistemas.json
  def index
    @sistemas = Sistema.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sistemas }
    end
  end

  # GET /sistemas/1
  # GET /sistemas/1.json
  def show
    @sistema = Sistema.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sistema }
    end
  end

  # GET /sistemas/new
  # GET /sistemas/new.json
  def new
    @sistema = Sistema.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sistema }
    end
  end

  # GET /sistemas/1/edit
  def edit
    @sistema = Sistema.find(params[:id])
  end

  # POST /sistemas
  # POST /sistemas.json
  def create
    @sistema = Sistema.new(params[:sistema])

    respond_to do |format|
      if @sistema.save
        format.html { redirect_to @sistema, notice: 'Sistema foi salvo com sucesso.' }
        format.json { render json: @sistema, status: :created, location: @sistema }
      else
        format.html { render action: "new" }
        format.json { render json: @sistema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sistemas/1
  # PUT /sistemas/1.json
  def update
    @sistema = Sistema.find(params[:id])

    respond_to do |format|
      if @sistema.update_attributes(params[:sistema])
        format.html { redirect_to @sistema, notice: 'Sistema foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sistema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sistemas/1
  # DELETE /sistemas/1.json
  def destroy
    @sistema = Sistema.find(params[:id])
    @sistema.destroy

    respond_to do |format|
      format.html { redirect_to sistemas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sistemas_helper.rb
module SistemasHelper
end

app/views/sistemas/_form.html.erb
<%= form_for(@sistema) do |f| %>
  <% if @sistema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sistema.errors.count, "error") %> Proibido este sistema de ser salvo:</h2>

      <ul>
      <% @sistema.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <div class="actions">
    <%= f.submit("Salvar") %>
  </div>
<% end %>

app/views/sistemas/edit.html.erb
<h1>Editar Sistema</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @sistema %> |
<%= link_to 'Voltar', sistemas_path %>

app/views/sistemas/index.html.erb
<h1>Lista Sistemas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Key</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sistemas.each do |sistema| %>
  <tr>
    <td><%= sistema.nome %></td>
    <td><%= sistema.key %></td>
    <td><%= link_to 'Mostrar', sistema %></td>
    <td><%= link_to 'Editar', edit_sistema_path(sistema) %></td>
    <td><%= link_to 'Apagar', sistema, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Sistema', new_sistema_path %>

app/views/sistemas/new.html.erb
<h1>Novo sistema</h1>

<%= render 'form' %>

<%= link_to 'Voltar', sistemas_path %>

app/views/sistemas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @sistema.nome %>
</p>

<p>
  <b>Key:</b>
  <%= @sistema.key %>
</p>


<%= link_to 'Editar', edit_sistema_path(@sistema) %> |
<%= link_to 'Voltar', sistemas_path %>