config/routes.rb
Auth::Application.routes.draw do

  get "users/desbloqueio"

  get "users/bloqueio"

  get "users/relatorio"

  get "users/mostrarDica"

  get "users/lembrar_senha"

  get "users/alter"

  get "home/index"
  
  get "authentications/loga"
  
  get "authentications/desloga"

  resources :logins

  resources :log_gerals

  resources :tipologs

  resources :users

  resources :statuses

  resources :usertypes

  resources :sistemas
  

  root :to => 'home#index'

end

app/views/menu/_menu.html.erb
<% if @_current_user != nil %>
                  <ul class="vmenu">
                    <li>
                      <%= link_to "Início", home_index_path %>
                    </li>
                    <li>
                      <%= link_to "Alterar Cadastro", edit_user_path(@_current_user.id ) %>
                    </li>
                    <li>
                      <%= link_to "Excluir Cadastro", user_path(0), method: :delete, data: { confirm: 'Desativar cadastro?' } %>
                    </li>
                                
                <% if @_current_user.usertype < 3 %>    
                    <li>
                      <%= link_to "Bloquear Usuario", users_bloqueio_path %>
                    </li>
                    <li>
                      <%= link_to "Desbloquear Usuario", users_desbloqueio_path %>
                    </li>
                    
                   	<% if @_current_user.usertype < 2 %> 
                    	<li>
                      <%= link_to "Alterar Usuário", users_alter_path %>
                    </li>
                    <li>
                      <%= link_to "Criar Sistema", new_sistema_path %>
                    </li>
                    <li>
                      <%= link_to "Relatorios", users_relatorio_path %>
                    </li>
                   <% end %> 
               <% end %>    
                    <li>
                      <%= link_to "Sair", login_path(0), method: :delete, data: { confirm: 'Deslogar?' } %>
                    </li>
                  </ul>
                  <!--%= @_current_user.id %-->
<% end %>