config/routes.rb
Auth::Application.routes.draw do

  get "users/desbloqueio"

  get "users/bloqueio"

  get "users/relatorio"

  get "users/mostrarDica"

  get "users/lembrar_senha"

  get "users/alter"

  get "home/index"
  
  get "authentications/loga"
  
  get "authentications/desloga"

  resources :logins

  resources :log_gerals

  resources :tipologs

  resources :users

  resources :statuses

  resources :usertypes

  resources :sistemas
  

  root :to => 'home#index'

end

app/models/login.rb
class Login < ActiveRecord::Base
  attr_accessible :cpf, :senha
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  skip_before_filter :require_login, :only => [:new, :create]
  
  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logins }
    end
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
    @login = Login.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @login }
    end
  end

  # GET /logins/new
  # GET /logins/new.json
  def new
    @login = Login.new
    
    if session[:current_user_id] != nil
      redirect_to root_url
      return
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @login }
    end
  end

  # GET /logins/1/edit
  def edit
    @login = Login.find(params[:id])
  end

  
  def authenticate(login)
    # Digest::SHA1.hexdigest(password) ==
    return User.first(:conditions => "cpf = '#{login.cpf}' and senha = '#{login.senha}'")
  end
  
  
  # "Cria" um login, ou seja, "loga o usuário"
  def create
    login=Login.new(params[:login])
    if user = authenticate(login) and user.status == 1
      flash[:notice] = "Voce entrou no sistema"
      # Registra o ID do usuário na sessão para que possa ser recuperado durante outras requisições
      session[:current_user_id] = user.id
      
      log = LogGeral.new
      log.data=DateTime.now
      log.tipolog=1
      log.user=user.id
      log.save
      
      redirect_to root_url
    else
      if(user != nil)
        case user.status
        when 2
          flash[:notice] = "Cadastro bloqueado"
        when 3
          flash[:notice] = "Cadastro desativado"
        else
          flash[:notice] = "Cadastro bloqueado e desativado"
        end
      else
        flash[:notice] = "Erro no login"
      end
      
      if user = User.find_by_cpf(login.cpf)
        log = LogGeral.new
        log.data=DateTime.now
        log.tipolog=2
        log.user=user.id
        log.save
        
        log = LogGeral.last(:conditions => ["user = :usuario and tipolog = 1",{:usuario => user.id}])
        if(log != nil)
          numero = LogGeral.all(:conditions => ["user = :usuario and tipolog = 2 and data >= :logdata",{:usuario => user.id, :logdata => log.data}]).length
          if numero > 4 and (user.status = 1 or user.status = 3)
            user.status+=1
            user.save
            flash[:notice] = "Usu&aacute;rio bloqueado por errar cinco vezes a senha"
            
            log = LogGeral.new
            log.data=DateTime.now
            log.tipolog=4
            log.user=user.id
            log.save
          end
        end
        
      end
      
      redirect_to new_login_path
    end
  end
  
  # PUT /logins/1
  # PUT /logins/1.json
  def update
    @login = Login.find(params[:id])

    respond_to do |format|
      if @login.update_attributes(params[:login])
        format.html { redirect_to @login, notice: 'Login foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # Remove o id do usuário da sessão
    session[:current_user_id] = nil
    flash[:notice] = "Voce saiu do sistema"
    redirect_to new_login_path
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> Proibido este login de ser salvo:</h2>

      <ul>
      <% @login.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cpf %><br />
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :senha %><br />
    <%= f.password_field :senha %>
  </div>
  <div class="actions">
    <%= f.submit "Login"%>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editar Login</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @login %> |
<%= link_to 'Voltar', logins_path %>

app/views/logins/index.html.erb
<h1>Lista Logins</h1>

<table>
  <tr>
    <th>CPF</th>
    <th>Senha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @logins.each do |login| %>
  <tr>
    <td><%= login.cpf %></td>
    <td><%= login.senha %></td>
    <td><%= link_to 'Mostrar', login %></td>
    <td><%= link_to 'Editar', edit_login_path(login) %></td>
    <td><%= link_to 'Apagar', login, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'Novo Login', new_login_path %>

app/views/logins/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Fazer Cadastro', new_user_path %>
<br />
<%= link_to 'Esqueci a Senha', users_lembrar_senha_path %>

<p id="notice"><%= notice %></p>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>CPF:</b>
  <%= @login.cpf %>
</p>

<p>
  <b>Senha:</b>
  <%= @login.senha %>
</p>


<%= link_to 'Editar', edit_login_path(@login) %> |
<%= link_to 'Voltar', logins_path %>