config/routes.rb
Auth::Application.routes.draw do

  get "users/desbloqueio"

  get "users/bloqueio"

  get "users/relatorio"

  get "users/mostrarDica"

  get "users/lembrar_senha"

  get "users/alter"

  get "home/index"
  
  get "authentications/loga"
  
  get "authentications/desloga"

  resources :logins

  resources :log_gerals

  resources :tipologs

  resources :users

  resources :statuses

  resources :usertypes

  resources :sistemas
  

  root :to => 'home#index'

end

app/models/tipolog.rb
class Tipolog < ActiveRecord::Base
  attr_accessible :nome
end

app/controllers/tipologs_controller.rb
class TipologsController < ApplicationController
  # GET /tipologs
  # GET /tipologs.json
  def index
    @tipologs = Tipolog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tipologs }
    end
  end

  # GET /tipologs/1
  # GET /tipologs/1.json
  def show
    @tipolog = Tipolog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tipolog }
    end
  end

  # GET /tipologs/new
  # GET /tipologs/new.json
  def new
    @tipolog = Tipolog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tipolog }
    end
  end

  # GET /tipologs/1/edit
  def edit
    @tipolog = Tipolog.find(params[:id])
  end

  # POST /tipologs
  # POST /tipologs.json
  def create
    @tipolog = Tipolog.new(params[:tipolog])

    respond_to do |format|
      if @tipolog.save
        format.html { redirect_to @tipolog, notice: 'Tipo log foi salvo com sucesso.' }
        format.json { render json: @tipolog, status: :created, location: @tipolog }
      else
        format.html { render action: "new" }
        format.json { render json: @tipolog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tipologs/1
  # PUT /tipologs/1.json
  def update
    @tipolog = Tipolog.find(params[:id])

    respond_to do |format|
      if @tipolog.update_attributes(params[:tipolog])
        format.html { redirect_to @tipolog, notice: 'Tipo log foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tipolog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipologs/1
  # DELETE /tipologs/1.json
  def destroy
    @tipolog = Tipolog.find(params[:id])
    @tipolog.destroy

    respond_to do |format|
      format.html { redirect_to tipologs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tipologs_helper.rb
module TipologsHelper
end

app/views/tipologs/_form.html.erb
<%= form_for(@tipolog) do |f| %>
  <% if @tipolog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipolog.errors.count, "error") %> Proibido este tipo de log de ser salvo:</h2>

      <ul>
      <% @tipolog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipologs/edit.html.erb
<h1>Editar Tipo Log</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @tipolog %> |
<%= link_to 'Voltar', tipologs_path %>

app/views/tipologs/index.html.erb
<h1>Lista Tipos de Log</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tipologs.each do |tipolog| %>
  <tr>
    <td><%= tipolog.nome %></td>
    <td><%= link_to 'Mostrar', tipolog %></td>
    <td><%= link_to 'Editar', edit_tipolog_path(tipolog) %></td>
    <td><%= link_to 'Apagar', tipolog, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Tipo de Log', new_tipolog_path %>

app/views/tipologs/new.html.erb
<h1>Novo tipo de Log</h1>

<%= render 'form' %>

<%= link_to 'Voltar', tipologs_path %>

app/views/tipologs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @tipolog.nome %>
</p>


<%= link_to 'Editar', edit_tipolog_path(@tipolog) %> |
<%= link_to 'Voltar', tipologs_path %>